### ISSUE TITLE
Updates not updateding

### ISSUE THREAD

**Issue by mbrevda** [nicholasconfer/mongoose-times#2]
It would seem that times are not updated when running `findOneAndUpdate`. My code looks as follows:

``` js
myModel.findOneAndUpdate({param: param}, {param2: param2}, callback)
```

Is there something I missed?

**Comment by nicholasconfer** [comment]
Pre/Post save events are not supported for findOneAndUpdate, so Mongoose-Times does not work for this.

Per the [Mongoose documentation](http://mongoosejs.com/docs/api.html#model_Model.findOneAndUpdate)

```
Although values are cast to their appropriate types when using the 
findAndModify helpers, the following are not applied:

defaults
setters
validators
middleware

If you need those features, use the traditional approach of first retrieving the document.
```

**Comment by mbrevda** [comment]
My bad, thanks!
