### ISSUE TITLE
Key rename doesn't remove standard keys

### ISSUE THREAD

**Issue by bbengfort** [nicholasconfer/mongoose-times#3]
I'm trying to rename the keys of created and lastModified to 'created_at' and 'updated_at' to fit with our Rails schema. You've correctly documented in your code how to do this by passing an object with the rename into the `plugin` function of the Schema. However, the old keys are still remaining on the document.

```
var mongoose = require("mongoose"),
    timestamps = require("mongoose-times");

var ExampleSchema = new Schema({});
ExampleSchema.plugin(timestamps, { created: "created_at", lastUpdated: "updated_at" });

var ExampleModel = mongoose.model("Example", ExampleSchema);

...

example = ExampleModel.create({}, console.log)
```

The resulting document is:

```
{
    _id: "538a098f7df920c5b8171397"
    lastUpdated: "2014-05-31T17:08:00.651Z"
    created: "2014-05-31T16:55:43.636Z"
    updated_at: "2014-05-31T17:08:00.649Z"
    created_at: "2014-05-31T16:55:43.634Z"
}
```

The old keys should not be on the document.

**Comment by nicholasconfer** [comment]
Hey Benjamin,

Sorry for the late reply, been a busy weekend.

I double checked, and this is not a bug in mongoose-times but rather a misunderstanding of the documentation.  When you use mongoose-times and want to use custom names for your created and lastUpdated keys, make sure you only include the line..

ExampleSchema.plugin(timestamps, { created: "created_at", lastUpdated: "updated_at" });

Do not also include the line

ExampleSchema.plugin(timestamps);

If you do so mongoose-times will add two sets of created and lastUpdated keys, as it only expects the plugin to be called once.

Nicholas.
